/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.proyecto.proyectolistatareas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




public class EditarLista extends javax.swing.JFrame {

    private ListaTareas listaTareasSeleccionada;
    
    /**
     * Creates new form EditarLista
     */
    public EditarLista(ListaTareas listaTareas) {
        
        initComponents();
        
        if(listaTareas == null) {
            // Si la lista de tareas es null, redirecciona al home screen
            this.dispose();
            new MainScreen().setVisible(true);
        }
        
        // Carga los datos de la lista de tareas seleccionada
        this.listaTareasSeleccionada = listaTareas;
        this.nombreListaTbx.setText(listaTareas.getNombre());
        cargarTablaListas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarTareaDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        editarNombreTbx = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        editarPrioridadCbx = new javax.swing.JComboBox<>();
        editarEstadoCbx = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        editarNotasTbx = new javax.swing.JTextField();
        editarGuardarBtn = new javax.swing.JButton();
        editarCancelarBtn = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        listaTareasTable = new javax.swing.JTable();
        resetTableBtn = new javax.swing.JButton();
        guardarTableBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tareaTbx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        notasTbx = new javax.swing.JTextField();
        agregarTareaBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        estadoCbx = new javax.swing.JComboBox<>();
        prioridadCbx = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreListaTbx = new javax.swing.JTextField();
        borrarBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();

        editarTareaDialog.setTitle("Editar Tarea");
        editarTareaDialog.setBounds(new java.awt.Rectangle(0, 25, 350, 440));
        editarTareaDialog.setPreferredSize(new java.awt.Dimension(350, 440));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Nombre: ");

        jLabel8.setText("Prioridad:");

        jLabel9.setText("Estado");

        editarPrioridadCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Alta" }));

        editarEstadoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En progreso", "Completada", "Cancelada", " " }));

        jLabel10.setText("Notas: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(editarNombreTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarEstadoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(editarPrioridadCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(editarNotasTbx))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(editarNombreTbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(editarPrioridadCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(editarEstadoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarNotasTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        editarGuardarBtn.setText("Guardar");
        editarGuardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarGuardarBtnActionPerformed(evt);
            }
        });

        editarCancelarBtn.setText("Cancelar");
        editarCancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCancelarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editarTareaDialogLayout = new javax.swing.GroupLayout(editarTareaDialog.getContentPane());
        editarTareaDialog.getContentPane().setLayout(editarTareaDialogLayout);
        editarTareaDialogLayout.setHorizontalGroup(
            editarTareaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarTareaDialogLayout.createSequentialGroup()
                .addGroup(editarTareaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editarTareaDialogLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editarTareaDialogLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(editarGuardarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editarCancelarBtn)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        editarTareaDialogLayout.setVerticalGroup(
            editarTareaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarTareaDialogLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editarTareaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarGuardarBtn)
                    .addComponent(editarCancelarBtn))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar Lista");

        listaTareasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listaTareasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaTareasTableMouseClicked(evt);
            }
        });
        tableScrollPane.setViewportView(listaTareasTable);

        resetTableBtn.setText("Reset");
        resetTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetTableBtnActionPerformed(evt);
            }
        });

        guardarTableBtn.setText("Guardar Cambios");
        guardarTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTableBtnActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Tarea: ");

        jLabel2.setText("Notas:");

        agregarTareaBtn.setText("Agregar");
        agregarTareaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTareaBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Estado: ");

        jLabel4.setText("Prioridad:");

        estadoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En progreso", "Completada", "Cancelada", " " }));

        prioridadCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Alta" }));

        jLabel5.setText("Agregar nueva tarea");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(notasTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(tareaTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estadoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prioridadCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(agregarTareaBtn)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tareaTbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prioridadCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(estadoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notasTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregarTareaBtn)
                .addGap(15, 15, 15))
        );

        jLabel6.setText("Nombre de Lista:");

        nombreListaTbx.setEditable(false);

        borrarBtn.setText("Borrar");
        borrarBtn.setEnabled(false);
        borrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBtnActionPerformed(evt);
            }
        });

        editarBtn.setText("Editar");
        editarBtn.setEnabled(false);
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreListaTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(borrarBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editarBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guardarTableBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(resetTableBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(volverBtn))
                        .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nombreListaTbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardarTableBtn)
                            .addComponent(resetTableBtn)
                            .addComponent(volverBtn)
                            .addComponent(borrarBtn)
                            .addComponent(editarBtn))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetTableBtnActionPerformed
        cargarTablaListas();
        tareaTbx.setText("");
        notasTbx.setText("");
    }//GEN-LAST:event_resetTableBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        this.dispose();
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_volverBtnActionPerformed

    private void borrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBtnActionPerformed
        
        // Obtiene el nombre de la tarea que se desea borrar
        String nombreTareaSeleccionada = listaTareasTable.getValueAt(listaTareasTable.getSelectedRow(), 0).toString();
        

        // Muestra un dialogo de confirmacion antes de borrar la tarea
        int resultado = JOptionPane.showConfirmDialog(this.getContentPane(), "Seguro que desea eliminar tarea: " + nombreTareaSeleccionada);
        

        // Si la respuesta fue si, ocurre lo siguiente
        if(resultado == JOptionPane.YES_OPTION) {
            // Obtiene el Model de la tabla, para modificar su contenido (Rows)
            DefaultTableModel model = (DefaultTableModel) this.listaTareasTable.getModel();
            // Remueve la tarea del Model de la tabla (Este cambio al modificar el model, se actualiza automaticamente en la tabla)
            model.removeRow(listaTareasTable.getSelectedRow());
            // Se vuelve a deshabilitar el boton de borrado, debido a que la tarea seleccionada, ya no existe
            borrarBtn.setEnabled(false);
        }
     
    }//GEN-LAST:event_borrarBtnActionPerformed

    private void listaTareasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaTareasTableMouseClicked
       
        // Si hay algun table row seleccionado, se habilita el boton de borrado, si no se deshabilita
        if(listaTareasTable.getSelectedRow() != -1) {
            borrarBtn.setEnabled(true);
            editarBtn.setEnabled(true);
        } else {
            borrarBtn.setEnabled(false);
            editarBtn.setEnabled(false);
        }
        
    }//GEN-LAST:event_listaTareasTableMouseClicked

    private void agregarTareaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTareaBtnActionPerformed
        
        
        String tarea = tareaTbx.getText();
        String prioridad = prioridadCbx.getSelectedItem().toString(); 
        String estado = estadoCbx.getSelectedItem().toString();
        String nota = notasTbx.getText();
        
        
        if(tarea != null && !tarea.equals("") && nota != null && !nota.equals("")) {
        
            // Obtiene el Model de la tabla, para modificar su contenido (Rows)
            DefaultTableModel model = (DefaultTableModel) this.listaTareasTable.getModel();

            // Agrega la tarea al Model de la tabla (Este cambio al modificar el model, se actualiza automaticamente en la tabla)
            model.addRow(new String [] {tarea, prioridad, estado, nota});

            // Se limpian los campos
            tareaTbx.setText("");
            notasTbx.setText("");
        
        } else {
            JOptionPane.showMessageDialog(getContentPane(), "Todos los campos son requeridos");
        }
        
        
    }//GEN-LAST:event_agregarTareaBtnActionPerformed

    private void guardarTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTableBtnActionPerformed
        
        Lista listaTareasList =  new Lista();
        
        // Recorre los rows de la tabla
        for (int i = 0; i < listaTareasTable.getRowCount(); i++) {  // Loop through the rows
            
            // Convierte los rows de la tabla en objetos ListaTareas y los agrega a la lista
            listaTareasList.agregarAlFinal(new Tarea(
                    listaTareasTable.getValueAt(i, 0).toString(), 
                    listaTareasTable.getValueAt(i, 1).toString(), 
                    listaTareasTable.getValueAt(i, 2).toString(), 
                    listaTareasTable.getValueAt(i, 3).toString()));         
      
        }

        FileHelper.guardarListaDeTareas(listaTareasSeleccionada.getId(), listaTareasList);
        
    }//GEN-LAST:event_guardarTableBtnActionPerformed

    private void editarGuardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarGuardarBtnActionPerformed
        
        
        String tarea = editarNombreTbx.getText();
        String prioridad = editarPrioridadCbx.getSelectedItem().toString(); 
        String estado = editarEstadoCbx.getSelectedItem().toString();
        String nota = editarNotasTbx.getText();
        
        
        if(tarea != null && !tarea.equals("") && nota != null && !nota.equals("")) {
            
            // Se obtiene el numero de row seleccionado en la tabla
            int rowIndex = listaTareasTable.getSelectedRow();

            // Se obtiene el modelo de la tabla y posteriormente se actualiza el valor utilizando el numero de row y el numero de columna
            listaTareasTable.getModel().setValueAt(tarea, rowIndex, 0);
            listaTareasTable.getModel().setValueAt(prioridad, rowIndex, 1);
            listaTareasTable.getModel().setValueAt(estado, rowIndex, 2);
            listaTareasTable.getModel().setValueAt(nota, rowIndex, 3);
            
            // Se cierra el dialog
            editarTareaDialog.dispose();
            
        } else {
            JOptionPane.showMessageDialog(getContentPane(), "Todos los campos son requeridos");
        }
        
        
    }//GEN-LAST:event_editarGuardarBtnActionPerformed

    private void editarCancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCancelarBtnActionPerformed
        editarTareaDialog.dispose();
    }//GEN-LAST:event_editarCancelarBtnActionPerformed

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        
        int rowIndex = listaTareasTable.getSelectedRow();
        String nombre = listaTareasTable.getModel().getValueAt(rowIndex, 0).toString();
        String prioridad = listaTareasTable.getModel().getValueAt(rowIndex, 1).toString();
        String estado = listaTareasTable.getModel().getValueAt(rowIndex, 2).toString();
        String notas = listaTareasTable.getModel().getValueAt(rowIndex, 3).toString();
        
        editarNombreTbx.setText(nombre);
        editarPrioridadCbx.setSelectedItem(prioridad);
        editarEstadoCbx.setSelectedItem(estado);
        editarNotasTbx.setText(notas);
        
        editarTareaDialog.setVisible(true);
        
    }//GEN-LAST:event_editarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarLista(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarTareaBtn;
    private javax.swing.JButton borrarBtn;
    private javax.swing.JButton editarBtn;
    private javax.swing.JButton editarCancelarBtn;
    private javax.swing.JComboBox<String> editarEstadoCbx;
    private javax.swing.JButton editarGuardarBtn;
    private javax.swing.JTextField editarNombreTbx;
    private javax.swing.JTextField editarNotasTbx;
    private javax.swing.JComboBox<String> editarPrioridadCbx;
    private javax.swing.JDialog editarTareaDialog;
    private javax.swing.JComboBox<String> estadoCbx;
    private javax.swing.JButton guardarTableBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable listaTareasTable;
    private javax.swing.JTextField nombreListaTbx;
    private javax.swing.JTextField notasTbx;
    private javax.swing.JComboBox<String> prioridadCbx;
    private javax.swing.JButton resetTableBtn;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTextField tareaTbx;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaListas() {
        
        String [] columnas = new String [] {"Tarea", "Prioridad", "Status", "Notas"};
        
        try{
            // Carga las listas de tareas desde el archivo de texto
            Lista listaDeTareasList = FileHelper.obtenerTareasPorLista(listaTareasSeleccionada);

            // Obtiene el tamaño de la lista
            int listaSize = listaDeTareasList.getTamanio();

            // Se define la matrix que contendra la informacion del Table
            String tableData [][] = new String [listaSize][4];


            // Recorre la lista para ir agregando cada elemento al array de la tabla
            for(int i = 0; i < listaSize; i++) {

                Tarea tarea = (Tarea) listaDeTareasList.getValor(i);
                tableData[i][0] = tarea.getTarea();
                tableData[i][1] = tarea.getPrioridad();
                tableData[i][2] = tarea.getEstado();
                tableData[i][3] = tarea.getNotas();

            }

            // Obtiene el modelo de la tabla y le agrega el array con la informacion obtenida anteriormente
            DefaultTableModel model = new DefaultTableModel(tableData, columnas);
            this.listaTareasTable.setModel(model);
        
        } catch (Exception ex) {
            // En caso de error se loggea la informacion del error en la consola
            System.err.println("Error cargando datos de la tabla");
            ex.printStackTrace();
        }
    }


}
